// Generated by gencpp from file robot_msgs/CurrentMap.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CURRENTMAP_H
#define ROBOT_MSGS_MESSAGE_CURRENTMAP_H

#include <ros/service_traits.h>


#include <robot_msgs/CurrentMapRequest.h>
#include <robot_msgs/CurrentMapResponse.h>


namespace robot_msgs
{

struct CurrentMap
{

typedef CurrentMapRequest Request;
typedef CurrentMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CurrentMap
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::CurrentMap > {
  static const char* value()
  {
    return "aa8aee7f6c8d5b8306117b46af679744";
  }

  static const char* value(const ::robot_msgs::CurrentMap&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::CurrentMap > {
  static const char* value()
  {
    return "robot_msgs/CurrentMap";
  }

  static const char* value(const ::robot_msgs::CurrentMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::CurrentMapRequest> should match
// service_traits::MD5Sum< ::robot_msgs::CurrentMap >
template<>
struct MD5Sum< ::robot_msgs::CurrentMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::CurrentMap >::value();
  }
  static const char* value(const ::robot_msgs::CurrentMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::CurrentMapRequest> should match
// service_traits::DataType< ::robot_msgs::CurrentMap >
template<>
struct DataType< ::robot_msgs::CurrentMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::CurrentMap >::value();
  }
  static const char* value(const ::robot_msgs::CurrentMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::CurrentMapResponse> should match
// service_traits::MD5Sum< ::robot_msgs::CurrentMap >
template<>
struct MD5Sum< ::robot_msgs::CurrentMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::CurrentMap >::value();
  }
  static const char* value(const ::robot_msgs::CurrentMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::CurrentMapResponse> should match
// service_traits::DataType< ::robot_msgs::CurrentMap >
template<>
struct DataType< ::robot_msgs::CurrentMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::CurrentMap >::value();
  }
  static const char* value(const ::robot_msgs::CurrentMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CURRENTMAP_H
