// Generated by gencpp from file robot_msgs/CurrentMapResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CURRENTMAPRESPONSE_H
#define ROBOT_MSGS_MESSAGE_CURRENTMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct CurrentMapResponse_
{
  typedef CurrentMapResponse_<ContainerAllocator> Type;

  CurrentMapResponse_()
    : map()  {
    }
  CurrentMapResponse_(const ContainerAllocator& _alloc)
    : map(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_type;
  _map_type map;





  typedef boost::shared_ptr< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentMapResponse_

typedef ::robot_msgs::CurrentMapResponse_<std::allocator<void> > CurrentMapResponse;

typedef boost::shared_ptr< ::robot_msgs::CurrentMapResponse > CurrentMapResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::CurrentMapResponse const> CurrentMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::CurrentMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::CurrentMapResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::CurrentMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.map == rhs.map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::CurrentMapResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::CurrentMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa8aee7f6c8d5b8306117b46af679744";
  }

  static const char* value(const ::robot_msgs::CurrentMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa8aee7f6c8d5b83ULL;
  static const uint64_t static_value2 = 0x06117b46af679744ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/CurrentMapResponse";
  }

  static const char* value(const ::robot_msgs::CurrentMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map\n"
;
  }

  static const char* value(const ::robot_msgs::CurrentMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::CurrentMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::CurrentMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "map: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CURRENTMAPRESPONSE_H
