// Generated by gencpp from file robot_msgs/DeleteMap.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_DELETEMAP_H
#define ROBOT_MSGS_MESSAGE_DELETEMAP_H

#include <ros/service_traits.h>


#include <robot_msgs/DeleteMapRequest.h>
#include <robot_msgs/DeleteMapResponse.h>


namespace robot_msgs
{

struct DeleteMap
{

typedef DeleteMapRequest Request;
typedef DeleteMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteMap
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::DeleteMap > {
  static const char* value()
  {
    return "4dc5c1ae2e494627977ff6a6eeb914ca";
  }

  static const char* value(const ::robot_msgs::DeleteMap&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::DeleteMap > {
  static const char* value()
  {
    return "robot_msgs/DeleteMap";
  }

  static const char* value(const ::robot_msgs::DeleteMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::DeleteMapRequest> should match
// service_traits::MD5Sum< ::robot_msgs::DeleteMap >
template<>
struct MD5Sum< ::robot_msgs::DeleteMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::DeleteMap >::value();
  }
  static const char* value(const ::robot_msgs::DeleteMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::DeleteMapRequest> should match
// service_traits::DataType< ::robot_msgs::DeleteMap >
template<>
struct DataType< ::robot_msgs::DeleteMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::DeleteMap >::value();
  }
  static const char* value(const ::robot_msgs::DeleteMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::DeleteMapResponse> should match
// service_traits::MD5Sum< ::robot_msgs::DeleteMap >
template<>
struct MD5Sum< ::robot_msgs::DeleteMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::DeleteMap >::value();
  }
  static const char* value(const ::robot_msgs::DeleteMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::DeleteMapResponse> should match
// service_traits::DataType< ::robot_msgs::DeleteMap >
template<>
struct DataType< ::robot_msgs::DeleteMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::DeleteMap >::value();
  }
  static const char* value(const ::robot_msgs::DeleteMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_DELETEMAP_H
