// Generated by gencpp from file robot_msgs/DeleteMapResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_DELETEMAPRESPONSE_H
#define ROBOT_MSGS_MESSAGE_DELETEMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct DeleteMapResponse_
{
  typedef DeleteMapResponse_<ContainerAllocator> Type;

  DeleteMapResponse_()
    : success(false)  {
    }
  DeleteMapResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteMapResponse_

typedef ::robot_msgs::DeleteMapResponse_<std::allocator<void> > DeleteMapResponse;

typedef boost::shared_ptr< ::robot_msgs::DeleteMapResponse > DeleteMapResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::DeleteMapResponse const> DeleteMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::DeleteMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::DeleteMapResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::DeleteMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::DeleteMapResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::DeleteMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::robot_msgs::DeleteMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/DeleteMapResponse";
  }

  static const char* value(const ::robot_msgs::DeleteMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::robot_msgs::DeleteMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::DeleteMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::DeleteMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_DELETEMAPRESPONSE_H
