// Generated by gencpp from file robot_msgs/DockingResult.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_DOCKINGRESULT_H
#define ROBOT_MSGS_MESSAGE_DOCKINGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct DockingResult_
{
  typedef DockingResult_<ContainerAllocator> Type;

  DockingResult_()
    : on_dock(false)  {
    }
  DockingResult_(const ContainerAllocator& _alloc)
    : on_dock(false)  {
  (void)_alloc;
    }



   typedef uint8_t _on_dock_type;
  _on_dock_type on_dock;





  typedef boost::shared_ptr< ::robot_msgs::DockingResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::DockingResult_<ContainerAllocator> const> ConstPtr;

}; // struct DockingResult_

typedef ::robot_msgs::DockingResult_<std::allocator<void> > DockingResult;

typedef boost::shared_ptr< ::robot_msgs::DockingResult > DockingResultPtr;
typedef boost::shared_ptr< ::robot_msgs::DockingResult const> DockingResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::DockingResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::DockingResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::DockingResult_<ContainerAllocator1> & lhs, const ::robot_msgs::DockingResult_<ContainerAllocator2> & rhs)
{
  return lhs.on_dock == rhs.on_dock;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::DockingResult_<ContainerAllocator1> & lhs, const ::robot_msgs::DockingResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::DockingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::DockingResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::DockingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::DockingResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::DockingResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::DockingResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::DockingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53dfbdecb11c4f6e454cade325832cf9";
  }

  static const char* value(const ::robot_msgs::DockingResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53dfbdecb11c4f6eULL;
  static const uint64_t static_value2 = 0x454cade325832cf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::DockingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/DockingResult";
  }

  static const char* value(const ::robot_msgs::DockingResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::DockingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool on_dock\n"
;
  }

  static const char* value(const ::robot_msgs::DockingResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::DockingResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on_dock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockingResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::DockingResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::DockingResult_<ContainerAllocator>& v)
  {
    s << indent << "on_dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on_dock);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_DOCKINGRESULT_H
