// Generated by gencpp from file robot_msgs/DockingFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_DOCKINGFEEDBACK_H
#define ROBOT_MSGS_MESSAGE_DOCKINGFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct DockingFeedback_
{
  typedef DockingFeedback_<ContainerAllocator> Type;

  DockingFeedback_()
    : docking_step(0)  {
    }
  DockingFeedback_(const ContainerAllocator& _alloc)
    : docking_step(0)  {
  (void)_alloc;
    }



   typedef int32_t _docking_step_type;
  _docking_step_type docking_step;





  typedef boost::shared_ptr< ::robot_msgs::DockingFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::DockingFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DockingFeedback_

typedef ::robot_msgs::DockingFeedback_<std::allocator<void> > DockingFeedback;

typedef boost::shared_ptr< ::robot_msgs::DockingFeedback > DockingFeedbackPtr;
typedef boost::shared_ptr< ::robot_msgs::DockingFeedback const> DockingFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::DockingFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::DockingFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::DockingFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::DockingFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.docking_step == rhs.docking_step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::DockingFeedback_<ContainerAllocator1> & lhs, const ::robot_msgs::DockingFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::DockingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::DockingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::DockingFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75a11098069abcb3a0accb1cd0548a67";
  }

  static const char* value(const ::robot_msgs::DockingFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75a11098069abcb3ULL;
  static const uint64_t static_value2 = 0xa0accb1cd0548a67ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/DockingFeedback";
  }

  static const char* value(const ::robot_msgs::DockingFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32 docking_step\n"
;
  }

  static const char* value(const ::robot_msgs::DockingFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.docking_step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockingFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::DockingFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::DockingFeedback_<ContainerAllocator>& v)
  {
    s << indent << "docking_step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.docking_step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_DOCKINGFEEDBACK_H
