// Generated by gencpp from file robot_msgs/GetGain.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_GETGAIN_H
#define ROBOT_MSGS_MESSAGE_GETGAIN_H

#include <ros/service_traits.h>


#include <robot_msgs/GetGainRequest.h>
#include <robot_msgs/GetGainResponse.h>


namespace robot_msgs
{

struct GetGain
{

typedef GetGainRequest Request;
typedef GetGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGain
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::GetGain > {
  static const char* value()
  {
    return "179ec88417e4994e631c5b039671a399";
  }

  static const char* value(const ::robot_msgs::GetGain&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::GetGain > {
  static const char* value()
  {
    return "robot_msgs/GetGain";
  }

  static const char* value(const ::robot_msgs::GetGain&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::GetGainRequest> should match
// service_traits::MD5Sum< ::robot_msgs::GetGain >
template<>
struct MD5Sum< ::robot_msgs::GetGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::GetGain >::value();
  }
  static const char* value(const ::robot_msgs::GetGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::GetGainRequest> should match
// service_traits::DataType< ::robot_msgs::GetGain >
template<>
struct DataType< ::robot_msgs::GetGainRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::GetGain >::value();
  }
  static const char* value(const ::robot_msgs::GetGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::GetGainResponse> should match
// service_traits::MD5Sum< ::robot_msgs::GetGain >
template<>
struct MD5Sum< ::robot_msgs::GetGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::GetGain >::value();
  }
  static const char* value(const ::robot_msgs::GetGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::GetGainResponse> should match
// service_traits::DataType< ::robot_msgs::GetGain >
template<>
struct DataType< ::robot_msgs::GetGainResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::GetGain >::value();
  }
  static const char* value(const ::robot_msgs::GetGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_GETGAIN_H
