// Generated by gencpp from file robot_msgs/GetGainResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_GETGAINRESPONSE_H
#define ROBOT_MSGS_MESSAGE_GETGAINRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct GetGainResponse_
{
  typedef GetGainResponse_<ContainerAllocator> Type;

  GetGainResponse_()
    : kp(0)
    , ki(0)
    , kd(0)  {
    }
  GetGainResponse_(const ContainerAllocator& _alloc)
    : kp(0)
    , ki(0)
    , kd(0)  {
  (void)_alloc;
    }



   typedef int32_t _kp_type;
  _kp_type kp;

   typedef int32_t _ki_type;
  _ki_type ki;

   typedef int32_t _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::robot_msgs::GetGainResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::GetGainResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetGainResponse_

typedef ::robot_msgs::GetGainResponse_<std::allocator<void> > GetGainResponse;

typedef boost::shared_ptr< ::robot_msgs::GetGainResponse > GetGainResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::GetGainResponse const> GetGainResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::GetGainResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::GetGainResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::GetGainResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::GetGainResponse_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::GetGainResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::GetGainResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::GetGainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::GetGainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::GetGainResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "179ec88417e4994e631c5b039671a399";
  }

  static const char* value(const ::robot_msgs::GetGainResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x179ec88417e4994eULL;
  static const uint64_t static_value2 = 0x631c5b039671a399ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/GetGainResponse";
  }

  static const char* value(const ::robot_msgs::GetGainResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 kp\n"
"int32 ki\n"
"int32 kd\n"
;
  }

  static const char* value(const ::robot_msgs::GetGainResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGainResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::GetGainResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::GetGainResponse_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_GETGAINRESPONSE_H
