// Generated by gencpp from file robot_msgs/HardwareDetected.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_HARDWAREDETECTED_H
#define ROBOT_MSGS_MESSAGE_HARDWAREDETECTED_H

#include <ros/service_traits.h>


#include <robot_msgs/HardwareDetectedRequest.h>
#include <robot_msgs/HardwareDetectedResponse.h>


namespace robot_msgs
{

struct HardwareDetected
{

typedef HardwareDetectedRequest Request;
typedef HardwareDetectedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HardwareDetected
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::HardwareDetected > {
  static const char* value()
  {
    return "c7a46eb97e96ced9baa3a1296f1c576c";
  }

  static const char* value(const ::robot_msgs::HardwareDetected&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::HardwareDetected > {
  static const char* value()
  {
    return "robot_msgs/HardwareDetected";
  }

  static const char* value(const ::robot_msgs::HardwareDetected&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::HardwareDetectedRequest> should match
// service_traits::MD5Sum< ::robot_msgs::HardwareDetected >
template<>
struct MD5Sum< ::robot_msgs::HardwareDetectedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::HardwareDetected >::value();
  }
  static const char* value(const ::robot_msgs::HardwareDetectedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::HardwareDetectedRequest> should match
// service_traits::DataType< ::robot_msgs::HardwareDetected >
template<>
struct DataType< ::robot_msgs::HardwareDetectedRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::HardwareDetected >::value();
  }
  static const char* value(const ::robot_msgs::HardwareDetectedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::HardwareDetectedResponse> should match
// service_traits::MD5Sum< ::robot_msgs::HardwareDetected >
template<>
struct MD5Sum< ::robot_msgs::HardwareDetectedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::HardwareDetected >::value();
  }
  static const char* value(const ::robot_msgs::HardwareDetectedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::HardwareDetectedResponse> should match
// service_traits::DataType< ::robot_msgs::HardwareDetected >
template<>
struct DataType< ::robot_msgs::HardwareDetectedResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::HardwareDetected >::value();
  }
  static const char* value(const ::robot_msgs::HardwareDetectedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_HARDWAREDETECTED_H
