// Generated by gencpp from file robot_msgs/HardwareDetectedResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_HARDWAREDETECTEDRESPONSE_H
#define ROBOT_MSGS_MESSAGE_HARDWAREDETECTEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct HardwareDetectedResponse_
{
  typedef HardwareDetectedResponse_<ContainerAllocator> Type;

  HardwareDetectedResponse_()
    : received(false)  {
    }
  HardwareDetectedResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;





  typedef boost::shared_ptr< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HardwareDetectedResponse_

typedef ::robot_msgs::HardwareDetectedResponse_<std::allocator<void> > HardwareDetectedResponse;

typedef boost::shared_ptr< ::robot_msgs::HardwareDetectedResponse > HardwareDetectedResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::HardwareDetectedResponse const> HardwareDetectedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/HardwareDetectedResponse";
  }

  static const char* value(const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n"
"\n"
;
  }

  static const char* value(const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HardwareDetectedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::HardwareDetectedResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_HARDWAREDETECTEDRESPONSE_H
