// Generated by gencpp from file robot_msgs/isAlive.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ISALIVE_H
#define ROBOT_MSGS_MESSAGE_ISALIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct isAlive_
{
  typedef isAlive_<ContainerAllocator> Type;

  isAlive_()
    : is_alive(false)
    , error()  {
    }
  isAlive_(const ContainerAllocator& _alloc)
    : is_alive(false)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_alive_type;
  _is_alive_type is_alive;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::robot_msgs::isAlive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::isAlive_<ContainerAllocator> const> ConstPtr;

}; // struct isAlive_

typedef ::robot_msgs::isAlive_<std::allocator<void> > isAlive;

typedef boost::shared_ptr< ::robot_msgs::isAlive > isAlivePtr;
typedef boost::shared_ptr< ::robot_msgs::isAlive const> isAliveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::isAlive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::isAlive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::isAlive_<ContainerAllocator1> & lhs, const ::robot_msgs::isAlive_<ContainerAllocator2> & rhs)
{
  return lhs.is_alive == rhs.is_alive &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::isAlive_<ContainerAllocator1> & lhs, const ::robot_msgs::isAlive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::isAlive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::isAlive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::isAlive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::isAlive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::isAlive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::isAlive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::isAlive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60775c3db7f51fcb9474847c3de8c5da";
  }

  static const char* value(const ::robot_msgs::isAlive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60775c3db7f51fcbULL;
  static const uint64_t static_value2 = 0x9474847c3de8c5daULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::isAlive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/isAlive";
  }

  static const char* value(const ::robot_msgs::isAlive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::isAlive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_alive\n"
"string error\n"
;
  }

  static const char* value(const ::robot_msgs::isAlive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::isAlive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_alive);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isAlive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::isAlive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::isAlive_<ContainerAllocator>& v)
  {
    s << indent << "is_alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_alive);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ISALIVE_H
