// Generated by gencpp from file robot_msgs/IsHardwareReadyRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ISHARDWAREREADYREQUEST_H
#define ROBOT_MSGS_MESSAGE_ISHARDWAREREADYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct IsHardwareReadyRequest_
{
  typedef IsHardwareReadyRequest_<ContainerAllocator> Type;

  IsHardwareReadyRequest_()
    {
    }
  IsHardwareReadyRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsHardwareReadyRequest_

typedef ::robot_msgs::IsHardwareReadyRequest_<std::allocator<void> > IsHardwareReadyRequest;

typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyRequest > IsHardwareReadyRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyRequest const> IsHardwareReadyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/IsHardwareReadyRequest";
  }

  static const char* value(const ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsHardwareReadyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_msgs::IsHardwareReadyRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ISHARDWAREREADYREQUEST_H
