// Generated by gencpp from file robot_msgs/IsHardwareReadyResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ISHARDWAREREADYRESPONSE_H
#define ROBOT_MSGS_MESSAGE_ISHARDWAREREADYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct IsHardwareReadyResponse_
{
  typedef IsHardwareReadyResponse_<ContainerAllocator> Type;

  IsHardwareReadyResponse_()
    : success(false)
    , description()  {
    }
  IsHardwareReadyResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsHardwareReadyResponse_

typedef ::robot_msgs::IsHardwareReadyResponse_<std::allocator<void> > IsHardwareReadyResponse;

typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyResponse > IsHardwareReadyResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::IsHardwareReadyResponse const> IsHardwareReadyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bccbb1e6ccd1459ac90cc79251ac541";
  }

  static const char* value(const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bccbb1e6ccd1459ULL;
  static const uint64_t static_value2 = 0xac90cc79251ac541ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/IsHardwareReadyResponse";
  }

  static const char* value(const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string description\n"
;
  }

  static const char* value(const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsHardwareReadyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::IsHardwareReadyResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ISHARDWAREREADYRESPONSE_H
