// Generated by gencpp from file robot_msgs/IsHardwareReady.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ISHARDWAREREADY_H
#define ROBOT_MSGS_MESSAGE_ISHARDWAREREADY_H

#include <ros/service_traits.h>


#include <robot_msgs/IsHardwareReadyRequest.h>
#include <robot_msgs/IsHardwareReadyResponse.h>


namespace robot_msgs
{

struct IsHardwareReady
{

typedef IsHardwareReadyRequest Request;
typedef IsHardwareReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsHardwareReady
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::IsHardwareReady > {
  static const char* value()
  {
    return "6bccbb1e6ccd1459ac90cc79251ac541";
  }

  static const char* value(const ::robot_msgs::IsHardwareReady&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::IsHardwareReady > {
  static const char* value()
  {
    return "robot_msgs/IsHardwareReady";
  }

  static const char* value(const ::robot_msgs::IsHardwareReady&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::IsHardwareReadyRequest> should match
// service_traits::MD5Sum< ::robot_msgs::IsHardwareReady >
template<>
struct MD5Sum< ::robot_msgs::IsHardwareReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::IsHardwareReady >::value();
  }
  static const char* value(const ::robot_msgs::IsHardwareReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::IsHardwareReadyRequest> should match
// service_traits::DataType< ::robot_msgs::IsHardwareReady >
template<>
struct DataType< ::robot_msgs::IsHardwareReadyRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::IsHardwareReady >::value();
  }
  static const char* value(const ::robot_msgs::IsHardwareReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::IsHardwareReadyResponse> should match
// service_traits::MD5Sum< ::robot_msgs::IsHardwareReady >
template<>
struct MD5Sum< ::robot_msgs::IsHardwareReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::IsHardwareReady >::value();
  }
  static const char* value(const ::robot_msgs::IsHardwareReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::IsHardwareReadyResponse> should match
// service_traits::DataType< ::robot_msgs::IsHardwareReady >
template<>
struct DataType< ::robot_msgs::IsHardwareReadyResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::IsHardwareReady >::value();
  }
  static const char* value(const ::robot_msgs::IsHardwareReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ISHARDWAREREADY_H
