// Generated by gencpp from file robot_msgs/MapsList.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MAPSLIST_H
#define ROBOT_MSGS_MESSAGE_MAPSLIST_H

#include <ros/service_traits.h>


#include <robot_msgs/MapsListRequest.h>
#include <robot_msgs/MapsListResponse.h>


namespace robot_msgs
{

struct MapsList
{

typedef MapsListRequest Request;
typedef MapsListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapsList
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::MapsList > {
  static const char* value()
  {
    return "95634a3fee1a76a7a235711f38773ee4";
  }

  static const char* value(const ::robot_msgs::MapsList&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::MapsList > {
  static const char* value()
  {
    return "robot_msgs/MapsList";
  }

  static const char* value(const ::robot_msgs::MapsList&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::MapsListRequest> should match
// service_traits::MD5Sum< ::robot_msgs::MapsList >
template<>
struct MD5Sum< ::robot_msgs::MapsListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::MapsList >::value();
  }
  static const char* value(const ::robot_msgs::MapsListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::MapsListRequest> should match
// service_traits::DataType< ::robot_msgs::MapsList >
template<>
struct DataType< ::robot_msgs::MapsListRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::MapsList >::value();
  }
  static const char* value(const ::robot_msgs::MapsListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::MapsListResponse> should match
// service_traits::MD5Sum< ::robot_msgs::MapsList >
template<>
struct MD5Sum< ::robot_msgs::MapsListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::MapsList >::value();
  }
  static const char* value(const ::robot_msgs::MapsListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::MapsListResponse> should match
// service_traits::DataType< ::robot_msgs::MapsList >
template<>
struct DataType< ::robot_msgs::MapsListResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::MapsList >::value();
  }
  static const char* value(const ::robot_msgs::MapsListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MAPSLIST_H
