// Generated by gencpp from file robot_msgs/MapsListRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MAPSLISTREQUEST_H
#define ROBOT_MSGS_MESSAGE_MAPSLISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct MapsListRequest_
{
  typedef MapsListRequest_<ContainerAllocator> Type;

  MapsListRequest_()
    {
    }
  MapsListRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_msgs::MapsListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::MapsListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapsListRequest_

typedef ::robot_msgs::MapsListRequest_<std::allocator<void> > MapsListRequest;

typedef boost::shared_ptr< ::robot_msgs::MapsListRequest > MapsListRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::MapsListRequest const> MapsListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::MapsListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::MapsListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::MapsListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::MapsListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::MapsListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_msgs::MapsListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/MapsListRequest";
  }

  static const char* value(const ::robot_msgs::MapsListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_msgs::MapsListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapsListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::MapsListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_msgs::MapsListRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MAPSLISTREQUEST_H
