// Generated by gencpp from file robot_msgs/Modes.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MODES_H
#define ROBOT_MSGS_MESSAGE_MODES_H

#include <ros/service_traits.h>


#include <robot_msgs/ModesRequest.h>
#include <robot_msgs/ModesResponse.h>


namespace robot_msgs
{

struct Modes
{

typedef ModesRequest Request;
typedef ModesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Modes
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Modes > {
  static const char* value()
  {
    return "324304a9077e74c893e232386723f0a2";
  }

  static const char* value(const ::robot_msgs::Modes&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Modes > {
  static const char* value()
  {
    return "robot_msgs/Modes";
  }

  static const char* value(const ::robot_msgs::Modes&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::ModesRequest> should match
// service_traits::MD5Sum< ::robot_msgs::Modes >
template<>
struct MD5Sum< ::robot_msgs::ModesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Modes >::value();
  }
  static const char* value(const ::robot_msgs::ModesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ModesRequest> should match
// service_traits::DataType< ::robot_msgs::Modes >
template<>
struct DataType< ::robot_msgs::ModesRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Modes >::value();
  }
  static const char* value(const ::robot_msgs::ModesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::ModesResponse> should match
// service_traits::MD5Sum< ::robot_msgs::Modes >
template<>
struct MD5Sum< ::robot_msgs::ModesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Modes >::value();
  }
  static const char* value(const ::robot_msgs::ModesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ModesResponse> should match
// service_traits::DataType< ::robot_msgs::Modes >
template<>
struct DataType< ::robot_msgs::ModesResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Modes >::value();
  }
  static const char* value(const ::robot_msgs::ModesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MODES_H
