// Generated by gencpp from file robot_msgs/ModesRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MODESREQUEST_H
#define ROBOT_MSGS_MESSAGE_MODESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct ModesRequest_
{
  typedef ModesRequest_<ContainerAllocator> Type;

  ModesRequest_()
    : is_start(false)
    , state()
    , param()  {
    }
  ModesRequest_(const ContainerAllocator& _alloc)
    : is_start(false)
    , state(_alloc)
    , param(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_start_type;
  _is_start_type is_start;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _param_type;
  _param_type param;





  typedef boost::shared_ptr< ::robot_msgs::ModesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::ModesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModesRequest_

typedef ::robot_msgs::ModesRequest_<std::allocator<void> > ModesRequest;

typedef boost::shared_ptr< ::robot_msgs::ModesRequest > ModesRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::ModesRequest const> ModesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::ModesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::ModesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::ModesRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::ModesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.is_start == rhs.is_start &&
    lhs.state == rhs.state &&
    lhs.param == rhs.param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::ModesRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::ModesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ModesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::ModesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ModesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::ModesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ModesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::ModesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::ModesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b64410bfc4d024ec3bf8633da53c73";
  }

  static const char* value(const ::robot_msgs::ModesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b64410bfc4d024ULL;
  static const uint64_t static_value2 = 0xec3bf8633da53c73ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::ModesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/ModesRequest";
  }

  static const char* value(const ::robot_msgs::ModesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::ModesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_start\n"
"string state\n"
"string param\n"
;
  }

  static const char* value(const ::robot_msgs::ModesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::ModesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_start);
      stream.next(m.state);
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::ModesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::ModesRequest_<ContainerAllocator>& v)
  {
    s << indent << "is_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_start);
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "param: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MODESREQUEST_H
