// Generated by gencpp from file robot_msgs/modes_status.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MODES_STATUS_H
#define ROBOT_MSGS_MESSAGE_MODES_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <robot_msgs/mode_status.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct modes_status_
{
  typedef modes_status_<ContainerAllocator> Type;

  modes_status_()
    : header()
    , modes()  {
    }
  modes_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , modes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::robot_msgs::mode_status_<ContainerAllocator>  _modes_type;
  _modes_type modes;





  typedef boost::shared_ptr< ::robot_msgs::modes_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::modes_status_<ContainerAllocator> const> ConstPtr;

}; // struct modes_status_

typedef ::robot_msgs::modes_status_<std::allocator<void> > modes_status;

typedef boost::shared_ptr< ::robot_msgs::modes_status > modes_statusPtr;
typedef boost::shared_ptr< ::robot_msgs::modes_status const> modes_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::modes_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::modes_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::modes_status_<ContainerAllocator1> & lhs, const ::robot_msgs::modes_status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.modes == rhs.modes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::modes_status_<ContainerAllocator1> & lhs, const ::robot_msgs::modes_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::modes_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::modes_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::modes_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::modes_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::modes_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::modes_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::modes_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1df3589f7b661a51051719c491977642";
  }

  static const char* value(const ::robot_msgs::modes_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1df3589f7b661a51ULL;
  static const uint64_t static_value2 = 0x051719c491977642ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::modes_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/modes_status";
  }

  static const char* value(const ::robot_msgs::modes_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::modes_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"robot_msgs/mode_status modes\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: robot_msgs/mode_status\n"
"bool docking\n"
"bool manual\n"
"bool navigation\n"
"bool mapping\n"
"bool stand_by\n"
;
  }

  static const char* value(const ::robot_msgs::modes_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::modes_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.modes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct modes_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::modes_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::modes_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "modes: ";
    s << std::endl;
    Printer< ::robot_msgs::mode_status_<ContainerAllocator> >::stream(s, indent + "  ", v.modes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MODES_STATUS_H
