// Generated by gencpp from file robot_msgs/NavigationStatusError.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_NAVIGATIONSTATUSERROR_H
#define ROBOT_MSGS_MESSAGE_NAVIGATIONSTATUSERROR_H

#include <ros/service_traits.h>


#include <robot_msgs/NavigationStatusErrorRequest.h>
#include <robot_msgs/NavigationStatusErrorResponse.h>


namespace robot_msgs
{

struct NavigationStatusError
{

typedef NavigationStatusErrorRequest Request;
typedef NavigationStatusErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavigationStatusError
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::NavigationStatusError > {
  static const char* value()
  {
    return "24527b03fd34734a9d2189497fa0891a";
  }

  static const char* value(const ::robot_msgs::NavigationStatusError&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::NavigationStatusError > {
  static const char* value()
  {
    return "robot_msgs/NavigationStatusError";
  }

  static const char* value(const ::robot_msgs::NavigationStatusError&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::NavigationStatusErrorRequest> should match
// service_traits::MD5Sum< ::robot_msgs::NavigationStatusError >
template<>
struct MD5Sum< ::robot_msgs::NavigationStatusErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::NavigationStatusError >::value();
  }
  static const char* value(const ::robot_msgs::NavigationStatusErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::NavigationStatusErrorRequest> should match
// service_traits::DataType< ::robot_msgs::NavigationStatusError >
template<>
struct DataType< ::robot_msgs::NavigationStatusErrorRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::NavigationStatusError >::value();
  }
  static const char* value(const ::robot_msgs::NavigationStatusErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::NavigationStatusErrorResponse> should match
// service_traits::MD5Sum< ::robot_msgs::NavigationStatusError >
template<>
struct MD5Sum< ::robot_msgs::NavigationStatusErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::NavigationStatusError >::value();
  }
  static const char* value(const ::robot_msgs::NavigationStatusErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::NavigationStatusErrorResponse> should match
// service_traits::DataType< ::robot_msgs::NavigationStatusError >
template<>
struct DataType< ::robot_msgs::NavigationStatusErrorResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::NavigationStatusError >::value();
  }
  static const char* value(const ::robot_msgs::NavigationStatusErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_NAVIGATIONSTATUSERROR_H
