// Generated by gencpp from file robot_msgs/NavigationStatusErrorResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_NAVIGATIONSTATUSERRORRESPONSE_H
#define ROBOT_MSGS_MESSAGE_NAVIGATIONSTATUSERRORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct NavigationStatusErrorResponse_
{
  typedef NavigationStatusErrorResponse_<ContainerAllocator> Type;

  NavigationStatusErrorResponse_()
    : error()
    , error_message()  {
    }
  NavigationStatusErrorResponse_(const ContainerAllocator& _alloc)
    : error(_alloc)
    , error_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationStatusErrorResponse_

typedef ::robot_msgs::NavigationStatusErrorResponse_<std::allocator<void> > NavigationStatusErrorResponse;

typedef boost::shared_ptr< ::robot_msgs::NavigationStatusErrorResponse > NavigationStatusErrorResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::NavigationStatusErrorResponse const> NavigationStatusErrorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.error == rhs.error &&
    lhs.error_message == rhs.error_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24527b03fd34734a9d2189497fa0891a";
  }

  static const char* value(const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24527b03fd34734aULL;
  static const uint64_t static_value2 = 0x9d2189497fa0891aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/NavigationStatusErrorResponse";
  }

  static const char* value(const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string error\n"
"string error_message\n"
"\n"
;
  }

  static const char* value(const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationStatusErrorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::NavigationStatusErrorResponse_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_NAVIGATIONSTATUSERRORRESPONSE_H
