// Generated by gencpp from file robot_msgs/RelayResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_RELAYRESPONSE_H
#define ROBOT_MSGS_MESSAGE_RELAYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct RelayResponse_
{
  typedef RelayResponse_<ContainerAllocator> Type;

  RelayResponse_()
    : status()
    , description()  {
    }
  RelayResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::robot_msgs::RelayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::RelayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RelayResponse_

typedef ::robot_msgs::RelayResponse_<std::allocator<void> > RelayResponse;

typedef boost::shared_ptr< ::robot_msgs::RelayResponse > RelayResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::RelayResponse const> RelayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::RelayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::RelayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::RelayResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::RelayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::RelayResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::RelayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RelayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RelayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RelayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RelayResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RelayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RelayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::RelayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d07d9e098ba771032b3d0a3e6050eb5";
  }

  static const char* value(const ::robot_msgs::RelayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d07d9e098ba7710ULL;
  static const uint64_t static_value2 = 0x32b3d0a3e6050eb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::RelayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/RelayResponse";
  }

  static const char* value(const ::robot_msgs::RelayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::RelayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"string description\n"
"\n"
;
  }

  static const char* value(const ::robot_msgs::RelayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::RelayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::RelayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::RelayResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_RELAYRESPONSE_H
