// Generated by gencpp from file robot_msgs/Relay.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_RELAY_H
#define ROBOT_MSGS_MESSAGE_RELAY_H

#include <ros/service_traits.h>


#include <robot_msgs/RelayRequest.h>
#include <robot_msgs/RelayResponse.h>


namespace robot_msgs
{

struct Relay
{

typedef RelayRequest Request;
typedef RelayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Relay
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Relay > {
  static const char* value()
  {
    return "3f2a44b2fa1cd7db6632dacb1c985817";
  }

  static const char* value(const ::robot_msgs::Relay&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Relay > {
  static const char* value()
  {
    return "robot_msgs/Relay";
  }

  static const char* value(const ::robot_msgs::Relay&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::RelayRequest> should match
// service_traits::MD5Sum< ::robot_msgs::Relay >
template<>
struct MD5Sum< ::robot_msgs::RelayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Relay >::value();
  }
  static const char* value(const ::robot_msgs::RelayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::RelayRequest> should match
// service_traits::DataType< ::robot_msgs::Relay >
template<>
struct DataType< ::robot_msgs::RelayRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Relay >::value();
  }
  static const char* value(const ::robot_msgs::RelayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::RelayResponse> should match
// service_traits::MD5Sum< ::robot_msgs::Relay >
template<>
struct MD5Sum< ::robot_msgs::RelayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Relay >::value();
  }
  static const char* value(const ::robot_msgs::RelayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::RelayResponse> should match
// service_traits::DataType< ::robot_msgs::Relay >
template<>
struct DataType< ::robot_msgs::RelayResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Relay >::value();
  }
  static const char* value(const ::robot_msgs::RelayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_RELAY_H
