// Generated by gencpp from file robot_msgs/RelayRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_RELAYREQUEST_H
#define ROBOT_MSGS_MESSAGE_RELAYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct RelayRequest_
{
  typedef RelayRequest_<ContainerAllocator> Type;

  RelayRequest_()
    : relevador(0)  {
    }
  RelayRequest_(const ContainerAllocator& _alloc)
    : relevador(0)  {
  (void)_alloc;
    }



   typedef int8_t _relevador_type;
  _relevador_type relevador;





  typedef boost::shared_ptr< ::robot_msgs::RelayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::RelayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelayRequest_

typedef ::robot_msgs::RelayRequest_<std::allocator<void> > RelayRequest;

typedef boost::shared_ptr< ::robot_msgs::RelayRequest > RelayRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::RelayRequest const> RelayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::RelayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::RelayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::RelayRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::RelayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.relevador == rhs.relevador;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::RelayRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::RelayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RelayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RelayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RelayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RelayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RelayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RelayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::RelayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5d86e098458f7b4dffed657a0c9cb2";
  }

  static const char* value(const ::robot_msgs::RelayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5d86e098458f7bULL;
  static const uint64_t static_value2 = 0x4dffed657a0c9cb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::RelayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/RelayRequest";
  }

  static const char* value(const ::robot_msgs::RelayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::RelayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 relevador\n"
;
  }

  static const char* value(const ::robot_msgs::RelayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::RelayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.relevador);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::RelayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::RelayRequest_<ContainerAllocator>& v)
  {
    s << indent << "relevador: ";
    Printer<int8_t>::stream(s, indent + "  ", v.relevador);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_RELAYREQUEST_H
