// Generated by gencpp from file robot_msgs/RemapRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_REMAPREQUEST_H
#define ROBOT_MSGS_MESSAGE_REMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct RemapRequest_
{
  typedef RemapRequest_<ContainerAllocator> Type;

  RemapRequest_()
    : is_start(false)  {
    }
  RemapRequest_(const ContainerAllocator& _alloc)
    : is_start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_start_type;
  _is_start_type is_start;





  typedef boost::shared_ptr< ::robot_msgs::RemapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::RemapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemapRequest_

typedef ::robot_msgs::RemapRequest_<std::allocator<void> > RemapRequest;

typedef boost::shared_ptr< ::robot_msgs::RemapRequest > RemapRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::RemapRequest const> RemapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::RemapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::RemapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::RemapRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::RemapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.is_start == rhs.is_start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::RemapRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::RemapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RemapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RemapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RemapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RemapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RemapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RemapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::RemapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa17c48d0ebde2d6ec887fa3ca761c08";
  }

  static const char* value(const ::robot_msgs::RemapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa17c48d0ebde2d6ULL;
  static const uint64_t static_value2 = 0xec887fa3ca761c08ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::RemapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/RemapRequest";
  }

  static const char* value(const ::robot_msgs::RemapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::RemapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_start\n"
;
  }

  static const char* value(const ::robot_msgs::RemapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::RemapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::RemapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::RemapRequest_<ContainerAllocator>& v)
  {
    s << indent << "is_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_REMAPREQUEST_H
