// Generated by gencpp from file robot_msgs/RobotShutdown.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOTSHUTDOWN_H
#define ROBOT_MSGS_MESSAGE_ROBOTSHUTDOWN_H

#include <ros/service_traits.h>


#include <robot_msgs/RobotShutdownRequest.h>
#include <robot_msgs/RobotShutdownResponse.h>


namespace robot_msgs
{

struct RobotShutdown
{

typedef RobotShutdownRequest Request;
typedef RobotShutdownResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotShutdown
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::RobotShutdown > {
  static const char* value()
  {
    return "6bccbb1e6ccd1459ac90cc79251ac541";
  }

  static const char* value(const ::robot_msgs::RobotShutdown&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::RobotShutdown > {
  static const char* value()
  {
    return "robot_msgs/RobotShutdown";
  }

  static const char* value(const ::robot_msgs::RobotShutdown&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::RobotShutdownRequest> should match
// service_traits::MD5Sum< ::robot_msgs::RobotShutdown >
template<>
struct MD5Sum< ::robot_msgs::RobotShutdownRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::RobotShutdown >::value();
  }
  static const char* value(const ::robot_msgs::RobotShutdownRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::RobotShutdownRequest> should match
// service_traits::DataType< ::robot_msgs::RobotShutdown >
template<>
struct DataType< ::robot_msgs::RobotShutdownRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::RobotShutdown >::value();
  }
  static const char* value(const ::robot_msgs::RobotShutdownRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::RobotShutdownResponse> should match
// service_traits::MD5Sum< ::robot_msgs::RobotShutdown >
template<>
struct MD5Sum< ::robot_msgs::RobotShutdownResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::RobotShutdown >::value();
  }
  static const char* value(const ::robot_msgs::RobotShutdownResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::RobotShutdownResponse> should match
// service_traits::DataType< ::robot_msgs::RobotShutdown >
template<>
struct DataType< ::robot_msgs::RobotShutdownResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::RobotShutdown >::value();
  }
  static const char* value(const ::robot_msgs::RobotShutdownResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOTSHUTDOWN_H
