// Generated by gencpp from file robot_msgs/robotPose.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOTPOSE_H
#define ROBOT_MSGS_MESSAGE_ROBOTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct robotPose_
{
  typedef robotPose_<ContainerAllocator> Type;

  robotPose_()
    : pose()
    , resolution(0.0)  {
    }
  robotPose_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , resolution(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _resolution_type;
  _resolution_type resolution;





  typedef boost::shared_ptr< ::robot_msgs::robotPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::robotPose_<ContainerAllocator> const> ConstPtr;

}; // struct robotPose_

typedef ::robot_msgs::robotPose_<std::allocator<void> > robotPose;

typedef boost::shared_ptr< ::robot_msgs::robotPose > robotPosePtr;
typedef boost::shared_ptr< ::robot_msgs::robotPose const> robotPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::robotPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::robotPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::robotPose_<ContainerAllocator1> & lhs, const ::robot_msgs::robotPose_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.resolution == rhs.resolution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::robotPose_<ContainerAllocator1> & lhs, const ::robot_msgs::robotPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::robotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::robotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::robotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::robotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::robotPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::robotPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::robotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d74e6214c9884a7c0f81a8910bcb3b84";
  }

  static const char* value(const ::robot_msgs::robotPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd74e6214c9884a7cULL;
  static const uint64_t static_value2 = 0x0f81a8910bcb3b84ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::robotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/robotPose";
  }

  static const char* value(const ::robot_msgs::robotPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::robotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"float32 resolution\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_msgs::robotPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::robotPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.resolution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::robotPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::robotPose_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOTPOSE_H
