// Generated by gencpp from file robot_msgs/SetGain.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SETGAIN_H
#define ROBOT_MSGS_MESSAGE_SETGAIN_H

#include <ros/service_traits.h>


#include <robot_msgs/SetGainRequest.h>
#include <robot_msgs/SetGainResponse.h>


namespace robot_msgs
{

struct SetGain
{

typedef SetGainRequest Request;
typedef SetGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGain
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::SetGain > {
  static const char* value()
  {
    return "a2f750cf2ccda6f044ac76934a961ff0";
  }

  static const char* value(const ::robot_msgs::SetGain&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::SetGain > {
  static const char* value()
  {
    return "robot_msgs/SetGain";
  }

  static const char* value(const ::robot_msgs::SetGain&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::SetGainRequest> should match
// service_traits::MD5Sum< ::robot_msgs::SetGain >
template<>
struct MD5Sum< ::robot_msgs::SetGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetGain >::value();
  }
  static const char* value(const ::robot_msgs::SetGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetGainRequest> should match
// service_traits::DataType< ::robot_msgs::SetGain >
template<>
struct DataType< ::robot_msgs::SetGainRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetGain >::value();
  }
  static const char* value(const ::robot_msgs::SetGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::SetGainResponse> should match
// service_traits::MD5Sum< ::robot_msgs::SetGain >
template<>
struct MD5Sum< ::robot_msgs::SetGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetGain >::value();
  }
  static const char* value(const ::robot_msgs::SetGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetGainResponse> should match
// service_traits::DataType< ::robot_msgs::SetGain >
template<>
struct DataType< ::robot_msgs::SetGainResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetGain >::value();
  }
  static const char* value(const ::robot_msgs::SetGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SETGAIN_H
