// Generated by gencpp from file robot_msgs/Shutdown.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SHUTDOWN_H
#define ROBOT_MSGS_MESSAGE_SHUTDOWN_H

#include <ros/service_traits.h>


#include <robot_msgs/ShutdownRequest.h>
#include <robot_msgs/ShutdownResponse.h>


namespace robot_msgs
{

struct Shutdown
{

typedef ShutdownRequest Request;
typedef ShutdownResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Shutdown
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Shutdown > {
  static const char* value()
  {
    return "6bccbb1e6ccd1459ac90cc79251ac541";
  }

  static const char* value(const ::robot_msgs::Shutdown&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Shutdown > {
  static const char* value()
  {
    return "robot_msgs/Shutdown";
  }

  static const char* value(const ::robot_msgs::Shutdown&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::ShutdownRequest> should match
// service_traits::MD5Sum< ::robot_msgs::Shutdown >
template<>
struct MD5Sum< ::robot_msgs::ShutdownRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Shutdown >::value();
  }
  static const char* value(const ::robot_msgs::ShutdownRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ShutdownRequest> should match
// service_traits::DataType< ::robot_msgs::Shutdown >
template<>
struct DataType< ::robot_msgs::ShutdownRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Shutdown >::value();
  }
  static const char* value(const ::robot_msgs::ShutdownRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::ShutdownResponse> should match
// service_traits::MD5Sum< ::robot_msgs::Shutdown >
template<>
struct MD5Sum< ::robot_msgs::ShutdownResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Shutdown >::value();
  }
  static const char* value(const ::robot_msgs::ShutdownResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ShutdownResponse> should match
// service_traits::DataType< ::robot_msgs::Shutdown >
template<>
struct DataType< ::robot_msgs::ShutdownResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Shutdown >::value();
  }
  static const char* value(const ::robot_msgs::ShutdownResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SHUTDOWN_H
