// Generated by gencpp from file robot_msgs/UpdateMap.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_UPDATEMAP_H
#define ROBOT_MSGS_MESSAGE_UPDATEMAP_H

#include <ros/service_traits.h>


#include <robot_msgs/UpdateMapRequest.h>
#include <robot_msgs/UpdateMapResponse.h>


namespace robot_msgs
{

struct UpdateMap
{

typedef UpdateMapRequest Request;
typedef UpdateMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateMap
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::UpdateMap > {
  static const char* value()
  {
    return "a4ce1b3ffd75a92f609cb75ae17890a9";
  }

  static const char* value(const ::robot_msgs::UpdateMap&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::UpdateMap > {
  static const char* value()
  {
    return "robot_msgs/UpdateMap";
  }

  static const char* value(const ::robot_msgs::UpdateMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::UpdateMapRequest> should match
// service_traits::MD5Sum< ::robot_msgs::UpdateMap >
template<>
struct MD5Sum< ::robot_msgs::UpdateMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robot_msgs::UpdateMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::UpdateMapRequest> should match
// service_traits::DataType< ::robot_msgs::UpdateMap >
template<>
struct DataType< ::robot_msgs::UpdateMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robot_msgs::UpdateMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::UpdateMapResponse> should match
// service_traits::MD5Sum< ::robot_msgs::UpdateMap >
template<>
struct MD5Sum< ::robot_msgs::UpdateMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robot_msgs::UpdateMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::UpdateMapResponse> should match
// service_traits::DataType< ::robot_msgs::UpdateMap >
template<>
struct DataType< ::robot_msgs::UpdateMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::UpdateMap >::value();
  }
  static const char* value(const ::robot_msgs::UpdateMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_UPDATEMAP_H
