// Generated by gencpp from file robot_msgs/WheelError.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_WHEELERROR_H
#define ROBOT_MSGS_MESSAGE_WHEELERROR_H

#include <ros/service_traits.h>


#include <robot_msgs/WheelErrorRequest.h>
#include <robot_msgs/WheelErrorResponse.h>


namespace robot_msgs
{

struct WheelError
{

typedef WheelErrorRequest Request;
typedef WheelErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WheelError
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::WheelError > {
  static const char* value()
  {
    return "1418f8f10b8efb185319b60d99ac214a";
  }

  static const char* value(const ::robot_msgs::WheelError&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::WheelError > {
  static const char* value()
  {
    return "robot_msgs/WheelError";
  }

  static const char* value(const ::robot_msgs::WheelError&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::WheelErrorRequest> should match
// service_traits::MD5Sum< ::robot_msgs::WheelError >
template<>
struct MD5Sum< ::robot_msgs::WheelErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::WheelError >::value();
  }
  static const char* value(const ::robot_msgs::WheelErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::WheelErrorRequest> should match
// service_traits::DataType< ::robot_msgs::WheelError >
template<>
struct DataType< ::robot_msgs::WheelErrorRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::WheelError >::value();
  }
  static const char* value(const ::robot_msgs::WheelErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::WheelErrorResponse> should match
// service_traits::MD5Sum< ::robot_msgs::WheelError >
template<>
struct MD5Sum< ::robot_msgs::WheelErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::WheelError >::value();
  }
  static const char* value(const ::robot_msgs::WheelErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::WheelErrorResponse> should match
// service_traits::DataType< ::robot_msgs::WheelError >
template<>
struct DataType< ::robot_msgs::WheelErrorResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::WheelError >::value();
  }
  static const char* value(const ::robot_msgs::WheelErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_WHEELERROR_H
