// Generated by gencpp from file robot_msgs/WheelDriver.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_WHEELDRIVER_H
#define ROBOT_MSGS_MESSAGE_WHEELDRIVER_H

#include <ros/service_traits.h>


#include <robot_msgs/WheelDriverRequest.h>
#include <robot_msgs/WheelDriverResponse.h>


namespace robot_msgs
{

struct WheelDriver
{

typedef WheelDriverRequest Request;
typedef WheelDriverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WheelDriver
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::WheelDriver > {
  static const char* value()
  {
    return "fa35b3456e4cbe35bdeeb16d2d0d52eb";
  }

  static const char* value(const ::robot_msgs::WheelDriver&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::WheelDriver > {
  static const char* value()
  {
    return "robot_msgs/WheelDriver";
  }

  static const char* value(const ::robot_msgs::WheelDriver&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::WheelDriverRequest> should match
// service_traits::MD5Sum< ::robot_msgs::WheelDriver >
template<>
struct MD5Sum< ::robot_msgs::WheelDriverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::WheelDriver >::value();
  }
  static const char* value(const ::robot_msgs::WheelDriverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::WheelDriverRequest> should match
// service_traits::DataType< ::robot_msgs::WheelDriver >
template<>
struct DataType< ::robot_msgs::WheelDriverRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::WheelDriver >::value();
  }
  static const char* value(const ::robot_msgs::WheelDriverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::WheelDriverResponse> should match
// service_traits::MD5Sum< ::robot_msgs::WheelDriver >
template<>
struct MD5Sum< ::robot_msgs::WheelDriverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::WheelDriver >::value();
  }
  static const char* value(const ::robot_msgs::WheelDriverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::WheelDriverResponse> should match
// service_traits::DataType< ::robot_msgs::WheelDriver >
template<>
struct DataType< ::robot_msgs::WheelDriverResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::WheelDriver >::value();
  }
  static const char* value(const ::robot_msgs::WheelDriverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_WHEELDRIVER_H
