// Generated by gencpp from file robot_msgs/WheelDriverRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_WHEELDRIVERREQUEST_H
#define ROBOT_MSGS_MESSAGE_WHEELDRIVERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct WheelDriverRequest_
{
  typedef WheelDriverRequest_<ContainerAllocator> Type;

  WheelDriverRequest_()
    : todo()  {
    }
  WheelDriverRequest_(const ContainerAllocator& _alloc)
    : todo(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _todo_type;
  _todo_type todo;





  typedef boost::shared_ptr< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WheelDriverRequest_

typedef ::robot_msgs::WheelDriverRequest_<std::allocator<void> > WheelDriverRequest;

typedef boost::shared_ptr< ::robot_msgs::WheelDriverRequest > WheelDriverRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::WheelDriverRequest const> WheelDriverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::WheelDriverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::WheelDriverRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::WheelDriverRequest_<ContainerAllocator2> & rhs)
{
  return lhs.todo == rhs.todo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::WheelDriverRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::WheelDriverRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be1abb59c2cee549ceeef382c8158a41";
  }

  static const char* value(const ::robot_msgs::WheelDriverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe1abb59c2cee549ULL;
  static const uint64_t static_value2 = 0xceeef382c8158a41ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/WheelDriverRequest";
  }

  static const char* value(const ::robot_msgs::WheelDriverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string todo\n"
;
  }

  static const char* value(const ::robot_msgs::WheelDriverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.todo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelDriverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::WheelDriverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::WheelDriverRequest_<ContainerAllocator>& v)
  {
    s << indent << "todo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.todo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_WHEELDRIVERREQUEST_H
