// Auto-generated. Do not edit!

// (in-package robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockingResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.on_dock = null;
    }
    else {
      if (initObj.hasOwnProperty('on_dock')) {
        this.on_dock = initObj.on_dock
      }
      else {
        this.on_dock = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockingResult
    // Serialize message field [on_dock]
    bufferOffset = _serializer.bool(obj.on_dock, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockingResult
    let len;
    let data = new DockingResult(null);
    // Deserialize message field [on_dock]
    data.on_dock = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msgs/DockingResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '53dfbdecb11c4f6e454cade325832cf9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    bool on_dock
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockingResult(null);
    if (msg.on_dock !== undefined) {
      resolved.on_dock = msg.on_dock;
    }
    else {
      resolved.on_dock = false
    }

    return resolved;
    }
};

module.exports = DockingResult;
