// Auto-generated. Do not edit!

// (in-package robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockingFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.docking_step = null;
    }
    else {
      if (initObj.hasOwnProperty('docking_step')) {
        this.docking_step = initObj.docking_step
      }
      else {
        this.docking_step = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockingFeedback
    // Serialize message field [docking_step]
    bufferOffset = _serializer.int32(obj.docking_step, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockingFeedback
    let len;
    let data = new DockingFeedback(null);
    // Deserialize message field [docking_step]
    data.docking_step = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msgs/DockingFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '75a11098069abcb3a0accb1cd0548a67';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 docking_step
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockingFeedback(null);
    if (msg.docking_step !== undefined) {
      resolved.docking_step = msg.docking_step;
    }
    else {
      resolved.docking_step = 0
    }

    return resolved;
    }
};

module.exports = DockingFeedback;
