// Auto-generated. Do not edit!

// (in-package robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockingGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.my_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('my_goal')) {
        this.my_goal = initObj.my_goal
      }
      else {
        this.my_goal = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockingGoal
    // Serialize message field [my_goal]
    bufferOffset = _serializer.int32(obj.my_goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockingGoal
    let len;
    let data = new DockingGoal(null);
    // Deserialize message field [my_goal]
    data.my_goal = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msgs/DockingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9863b252ba846a4c8bc8109133e46d2e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 my_goal
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockingGoal(null);
    if (msg.my_goal !== undefined) {
      resolved.my_goal = msg.my_goal;
    }
    else {
      resolved.my_goal = 0
    }

    return resolved;
    }
};

module.exports = DockingGoal;
