// Generated by gencpp from file zlac706_driver_control/WheelDriverResponse.msg
// DO NOT EDIT!


#ifndef ZLAC706_DRIVER_CONTROL_MESSAGE_WHEELDRIVERRESPONSE_H
#define ZLAC706_DRIVER_CONTROL_MESSAGE_WHEELDRIVERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zlac706_driver_control
{
template <class ContainerAllocator>
struct WheelDriverResponse_
{
  typedef WheelDriverResponse_<ContainerAllocator> Type;

  WheelDriverResponse_()
    : status(false)  {
    }
  WheelDriverResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WheelDriverResponse_

typedef ::zlac706_driver_control::WheelDriverResponse_<std::allocator<void> > WheelDriverResponse;

typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverResponse > WheelDriverResponsePtr;
typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverResponse const> WheelDriverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator1> & lhs, const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator1> & lhs, const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zlac706_driver_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zlac706_driver_control/WheelDriverResponse";
  }

  static const char* value(const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
"\n"
;
  }

  static const char* value(const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelDriverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zlac706_driver_control::WheelDriverResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZLAC706_DRIVER_CONTROL_MESSAGE_WHEELDRIVERRESPONSE_H
