// Generated by gencpp from file zlac706_driver_control/WheelDriverRequest.msg
// DO NOT EDIT!


#ifndef ZLAC706_DRIVER_CONTROL_MESSAGE_WHEELDRIVERREQUEST_H
#define ZLAC706_DRIVER_CONTROL_MESSAGE_WHEELDRIVERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zlac706_driver_control
{
template <class ContainerAllocator>
struct WheelDriverRequest_
{
  typedef WheelDriverRequest_<ContainerAllocator> Type;

  WheelDriverRequest_()
    : rueda()  {
    }
  WheelDriverRequest_(const ContainerAllocator& _alloc)
    : rueda(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _rueda_type;
  _rueda_type rueda;





  typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WheelDriverRequest_

typedef ::zlac706_driver_control::WheelDriverRequest_<std::allocator<void> > WheelDriverRequest;

typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverRequest > WheelDriverRequestPtr;
typedef boost::shared_ptr< ::zlac706_driver_control::WheelDriverRequest const> WheelDriverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator1> & lhs, const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rueda == rhs.rueda;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator1> & lhs, const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zlac706_driver_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee23d24ce8168530aa0a49928ec1a2da";
  }

  static const char* value(const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee23d24ce8168530ULL;
  static const uint64_t static_value2 = 0xaa0a49928ec1a2daULL;
};

template<class ContainerAllocator>
struct DataType< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zlac706_driver_control/WheelDriverRequest";
  }

  static const char* value(const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string rueda\n"
;
  }

  static const char* value(const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rueda);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelDriverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zlac706_driver_control::WheelDriverRequest_<ContainerAllocator>& v)
  {
    s << indent << "rueda: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.rueda);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZLAC706_DRIVER_CONTROL_MESSAGE_WHEELDRIVERREQUEST_H
