// Generated by gencpp from file rplidar_ros/motor_speedRequest.msg
// DO NOT EDIT!


#ifndef RPLIDAR_ROS_MESSAGE_MOTOR_SPEEDREQUEST_H
#define RPLIDAR_ROS_MESSAGE_MOTOR_SPEEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rplidar_ros
{
template <class ContainerAllocator>
struct motor_speedRequest_
{
  typedef motor_speedRequest_<ContainerAllocator> Type;

  motor_speedRequest_()
    : speed(0)  {
    }
  motor_speedRequest_(const ContainerAllocator& _alloc)
    : speed(0)  {
  (void)_alloc;
    }



   typedef uint16_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_speedRequest_

typedef ::rplidar_ros::motor_speedRequest_<std::allocator<void> > motor_speedRequest;

typedef boost::shared_ptr< ::rplidar_ros::motor_speedRequest > motor_speedRequestPtr;
typedef boost::shared_ptr< ::rplidar_ros::motor_speedRequest const> motor_speedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rplidar_ros::motor_speedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rplidar_ros::motor_speedRequest_<ContainerAllocator1> & lhs, const ::rplidar_ros::motor_speedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rplidar_ros::motor_speedRequest_<ContainerAllocator1> & lhs, const ::rplidar_ros::motor_speedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rplidar_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0026b653807c4b3ac6672ca0fd38046c";
  }

  static const char* value(const ::rplidar_ros::motor_speedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0026b653807c4b3aULL;
  static const uint64_t static_value2 = 0xc6672ca0fd38046cULL;
};

template<class ContainerAllocator>
struct DataType< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rplidar_ros/motor_speedRequest";
  }

  static const char* value(const ::rplidar_ros::motor_speedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 speed\n"
;
  }

  static const char* value(const ::rplidar_ros::motor_speedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_speedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rplidar_ros::motor_speedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rplidar_ros::motor_speedRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPLIDAR_ROS_MESSAGE_MOTOR_SPEEDREQUEST_H
