# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from controller/DatosControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DatosControl(genpy.Message):
  _md5sum = "837132ccf45cf52b00c57285b91233c7"
  _type = "controller/DatosControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 linearVel
float64 angularVel
float64 angle
float64 x
float64 xd
float64 y
float64 yd
float64 ex
float64 ey
float64 evx
float64 evy
float64 eT

"""
  __slots__ = ['linearVel','angularVel','angle','x','xd','y','yd','ex','ey','evx','evy','eT']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       linearVel,angularVel,angle,x,xd,y,yd,ex,ey,evx,evy,eT

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DatosControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.linearVel is None:
        self.linearVel = 0.
      if self.angularVel is None:
        self.angularVel = 0.
      if self.angle is None:
        self.angle = 0.
      if self.x is None:
        self.x = 0.
      if self.xd is None:
        self.xd = 0.
      if self.y is None:
        self.y = 0.
      if self.yd is None:
        self.yd = 0.
      if self.ex is None:
        self.ex = 0.
      if self.ey is None:
        self.ey = 0.
      if self.evx is None:
        self.evx = 0.
      if self.evy is None:
        self.evy = 0.
      if self.eT is None:
        self.eT = 0.
    else:
      self.linearVel = 0.
      self.angularVel = 0.
      self.angle = 0.
      self.x = 0.
      self.xd = 0.
      self.y = 0.
      self.yd = 0.
      self.ex = 0.
      self.ey = 0.
      self.evx = 0.
      self.evy = 0.
      self.eT = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.linearVel, _x.angularVel, _x.angle, _x.x, _x.xd, _x.y, _x.yd, _x.ex, _x.ey, _x.evx, _x.evy, _x.eT))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.linearVel, _x.angularVel, _x.angle, _x.x, _x.xd, _x.y, _x.yd, _x.ex, _x.ey, _x.evx, _x.evy, _x.eT,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.linearVel, _x.angularVel, _x.angle, _x.x, _x.xd, _x.y, _x.yd, _x.ex, _x.ey, _x.evx, _x.evy, _x.eT))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.linearVel, _x.angularVel, _x.angle, _x.x, _x.xd, _x.y, _x.yd, _x.ex, _x.ey, _x.evx, _x.evy, _x.eT,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
