# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msgs/mode_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mode_status(genpy.Message):
  _md5sum = "401e19daf4dfa2be65d1fcd32ec6dd29"
  _type = "robot_msgs/mode_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool docking
bool manual
bool navigation
bool mapping
bool stand_by"""
  __slots__ = ['docking','manual','navigation','mapping','stand_by']
  _slot_types = ['bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       docking,manual,navigation,mapping,stand_by

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mode_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.docking is None:
        self.docking = False
      if self.manual is None:
        self.manual = False
      if self.navigation is None:
        self.navigation = False
      if self.mapping is None:
        self.mapping = False
      if self.stand_by is None:
        self.stand_by = False
    else:
      self.docking = False
      self.manual = False
      self.navigation = False
      self.mapping = False
      self.stand_by = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.docking, _x.manual, _x.navigation, _x.mapping, _x.stand_by))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.docking, _x.manual, _x.navigation, _x.mapping, _x.stand_by,) = _get_struct_5B().unpack(str[start:end])
      self.docking = bool(self.docking)
      self.manual = bool(self.manual)
      self.navigation = bool(self.navigation)
      self.mapping = bool(self.mapping)
      self.stand_by = bool(self.stand_by)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.docking, _x.manual, _x.navigation, _x.mapping, _x.stand_by))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.docking, _x.manual, _x.navigation, _x.mapping, _x.stand_by,) = _get_struct_5B().unpack(str[start:end])
      self.docking = bool(self.docking)
      self.manual = bool(self.manual)
      self.navigation = bool(self.navigation)
      self.mapping = bool(self.mapping)
      self.stand_by = bool(self.stand_by)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
