; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude DockingGoal.msg.html

(cl:defclass <DockingGoal> (roslisp-msg-protocol:ros-message)
  ((my_goal
    :reader my_goal
    :initarg :my_goal
    :type cl:integer
    :initform 0))
)

(cl:defclass DockingGoal (<DockingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<DockingGoal> is deprecated: use robot_msgs-msg:DockingGoal instead.")))

(cl:ensure-generic-function 'my_goal-val :lambda-list '(m))
(cl:defmethod my_goal-val ((m <DockingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:my_goal-val is deprecated.  Use robot_msgs-msg:my_goal instead.")
  (my_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockingGoal>) ostream)
  "Serializes a message object of type '<DockingGoal>"
  (cl:let* ((signed (cl:slot-value msg 'my_goal)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockingGoal>) istream)
  "Deserializes a message object of type '<DockingGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'my_goal) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockingGoal>)))
  "Returns string type for a message object of type '<DockingGoal>"
  "robot_msgs/DockingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockingGoal)))
  "Returns string type for a message object of type 'DockingGoal"
  "robot_msgs/DockingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockingGoal>)))
  "Returns md5sum for a message object of type '<DockingGoal>"
  "9863b252ba846a4c8bc8109133e46d2e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockingGoal)))
  "Returns md5sum for a message object of type 'DockingGoal"
  "9863b252ba846a4c8bc8109133e46d2e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockingGoal>)))
  "Returns full string definition for message of type '<DockingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 my_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockingGoal)))
  "Returns full string definition for message of type 'DockingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 my_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockingGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DockingGoal
    (cl:cons ':my_goal (my_goal msg))
))
