; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude DockingResult.msg.html

(cl:defclass <DockingResult> (roslisp-msg-protocol:ros-message)
  ((on_dock
    :reader on_dock
    :initarg :on_dock
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass DockingResult (<DockingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<DockingResult> is deprecated: use robot_msgs-msg:DockingResult instead.")))

(cl:ensure-generic-function 'on_dock-val :lambda-list '(m))
(cl:defmethod on_dock-val ((m <DockingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:on_dock-val is deprecated.  Use robot_msgs-msg:on_dock instead.")
  (on_dock m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockingResult>) ostream)
  "Serializes a message object of type '<DockingResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'on_dock) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockingResult>) istream)
  "Deserializes a message object of type '<DockingResult>"
    (cl:setf (cl:slot-value msg 'on_dock) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockingResult>)))
  "Returns string type for a message object of type '<DockingResult>"
  "robot_msgs/DockingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockingResult)))
  "Returns string type for a message object of type 'DockingResult"
  "robot_msgs/DockingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockingResult>)))
  "Returns md5sum for a message object of type '<DockingResult>"
  "53dfbdecb11c4f6e454cade325832cf9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockingResult)))
  "Returns md5sum for a message object of type 'DockingResult"
  "53dfbdecb11c4f6e454cade325832cf9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockingResult>)))
  "Returns full string definition for message of type '<DockingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool on_dock~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockingResult)))
  "Returns full string definition for message of type 'DockingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool on_dock~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockingResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DockingResult
    (cl:cons ':on_dock (on_dock msg))
))
