; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude DockingFeedback.msg.html

(cl:defclass <DockingFeedback> (roslisp-msg-protocol:ros-message)
  ((docking_step
    :reader docking_step
    :initarg :docking_step
    :type cl:integer
    :initform 0))
)

(cl:defclass DockingFeedback (<DockingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<DockingFeedback> is deprecated: use robot_msgs-msg:DockingFeedback instead.")))

(cl:ensure-generic-function 'docking_step-val :lambda-list '(m))
(cl:defmethod docking_step-val ((m <DockingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:docking_step-val is deprecated.  Use robot_msgs-msg:docking_step instead.")
  (docking_step m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockingFeedback>) ostream)
  "Serializes a message object of type '<DockingFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'docking_step)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockingFeedback>) istream)
  "Deserializes a message object of type '<DockingFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'docking_step) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockingFeedback>)))
  "Returns string type for a message object of type '<DockingFeedback>"
  "robot_msgs/DockingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockingFeedback)))
  "Returns string type for a message object of type 'DockingFeedback"
  "robot_msgs/DockingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockingFeedback>)))
  "Returns md5sum for a message object of type '<DockingFeedback>"
  "75a11098069abcb3a0accb1cd0548a67")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockingFeedback)))
  "Returns md5sum for a message object of type 'DockingFeedback"
  "75a11098069abcb3a0accb1cd0548a67")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockingFeedback>)))
  "Returns full string definition for message of type '<DockingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 docking_step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockingFeedback)))
  "Returns full string definition for message of type 'DockingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 docking_step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockingFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DockingFeedback
    (cl:cons ':docking_step (docking_step msg))
))
